# data.py

from typing import Optional

EVENTS = [
  {
    "id": 1,
    "name": "Web Development Workshop",
    "date": "2025-05-20T14:00:00Z",
    "time": "2:00 PM - 4:00 PM",
    "location": "Tech Hub, Downtown",
    "price": 25,
    "originalPrice": 40,
    "category": "Technology",
    "image_url": "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800",
    "organizer": "Code Masters Academy",
    "attendees": 45,
    "tags": ["coding", "frontend", "webdev", "react"]
  },
  {
    "id": 2,
    "name": "Annual Music Festival",
    "date": "2025-07-15T17:30:00Z",
    "time": "5:30 PM - 11:00 PM",
    "location": "Central Park",
    "price": 75,
    "originalPrice": 90,
    "category": "Music",
    "image_url": "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800",
    "organizer": "City Events",
    "attendees": 1200,
    "tags": ["music", "live", "festival", "outdoor"]
  },
  {
    "id": 3,
    "name": "Community Yoga Session",
    "date": "2025-03-25T08:00:00Z",
    "time": "8:00 AM - 9:30 AM",
    "location": "Wellness Center",
    "price": 0,
    "category": "Health",
    "image_url": "https://images.unsplash.com/photo-1599447421416-3414500d18a5?w=800",
    "organizer": "Mindful Living",
    "attendees": 30,
    "tags": ["yoga", "wellness", "fitness", "morning"]
  },
  {
    "id": 4,
    "name": "Startup Networking Mixer",
    "date": "2025-04-10T18:00:00Z",
    "time": "6:00 PM - 9:00 PM",
    "location": "Innovation Center",
    "price": 15,
    "category": "Business",
    "organizer": "Founders Network",
    "attendees": 85,
    "tags": ["networking", "startup", "business", "entrepreneurs"]
  },
  {
    "id": 5,
    "name": "Charity Run for Education",
    "date": "2025-06-05T07:30:00Z",
    "time": "7:30 AM - 11:00 AM",
    "location": "Riverside Park",
    "price": 30,
    "originalPrice": 30,
    "category": "Sports",
    "image_url": "https://images.unsplash.com/photo-1519056233533-e30bb4549a37?w=800",
    "organizer": "Education First Foundation",
    "attendees": 350,
    "tags": ["charity", "running", "education", "community"]
  },
  {
    "id": 6,
    "name": "AI and Machine Learning Conference",
    "date": "2025-08-21T09:00:00Z",
    "time": "9:00 AM - 5:00 PM",
    "location": "Convention Center",
    "price": 199,
    "originalPrice": 299,
    "category": "Technology",
    "image_url": "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800",
    "organizer": "Future Tech Alliance",
    "attendees": 750,
    "tags": ["ai", "ml", "technology", "conference"]
  },
  {
    "id": 7,
    "name": "Local Film Festival",
    "date": "2025-05-15T18:30:00Z",
    "time": "6:30 PM - 10:00 PM",
    "location": "Arts Cinema",
    "price": 20,
    "category": "Arts",
    "image_url": "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800",
    "organizer": "Independent Filmmakers Guild",
    "attendees": 180,
    "tags": ["film", "cinema", "arts", "independent"]
  },
  {
    "id": 8,
    "name": "Food & Wine Tasting Event",
    "date": "2025-04-28T17:00:00Z",
    "time": "5:00 PM - 8:00 PM",
    "location": "Grand Hotel Ballroom",
    "price": 85,
    "category": "Food & Drink",
    "image_url": "https://images.unsplash.com/photo-1592483478492-2c40211455e9?w=800",
    "organizer": "Culinary Association",
    "attendees": 120,
    "tags": ["food", "wine", "tasting", "gourmet"]
  },
  {
    "id": 9,
    "name": "Career Fair for Graduates",
    "date": "2025-06-15T10:00:00Z",
    "time": "10:00 AM - 4:00 PM",
    "location": "University Campus",
    "price": 0,
    "category": "Career",
    "organizer": "University Career Services",
    "attendees": 500,
    "tags": ["career", "jobs", "networking", "graduates"]
  },
  {
    "id": 10,
    "name": "Weekend Art Workshop",
    "date": "2025-05-10T13:00:00Z",
    "time": "1:00 PM - 5:00 PM",
    "location": "Community Art Studio",
    "price": 45,
    "originalPrice": 60,
    "category": "Arts",
    "image_url": "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800",
    "organizer": "Creative Arts Collective",
    "attendees": 25,
    "tags": ["art", "workshop", "creative", "painting"]
  }
]




USERS = [
    {
        "id": 1,
        "username": "Rohit yadav",
        "email": "rohit@example.com",
        "interests": ["Music", "Technology", "Health"],
        "community_ids": [1, 2],
    },
    {
        "id": 2,
        "username": "jane_smith",
        "email": "jane@example.com",
        "interests": ["Art", "Literature", "Photography"],
        "community_ids": [3],
    },
    {
        "id": 3,
        "username": "joh_doe",
        "email": "joh@example.com",
        "interests": ["Music", "Technology", "Health"],
        "community_ids": [1, 2],
    },
    # Additional 30 Users
    {
        "id": 4,
        "username": "alice_wonder",
        "email": "alice.wonder@example.com",
        "interests": ["Travel", "Cooking", "Yoga"],
        "community_ids": [4, 5],
    },
    {
        "id": 5,
        "username": "bob_builder",
        "email": "bob.builder@example.com",
        "interests": ["DIY", "Gardening", "Technology"],
        "community_ids": [2, 6],
    },
    {
        "id": 6,
        "username": "charlie_brown",
        "email": "charlie.brown@example.com",
        "interests": ["Comics", "Music", "Sports"],
        "community_ids": [1, 7],
    },
    {
        "id": 7,
        "username": "diana_prince",
        "email": "diana.prince@example.com",
        "interests": ["Fitness", "Health", "Travel"],
        "community_ids": [4, 5],
    },
    {
        "id": 8,
        "username": "edward_scissorhands",
        "email": "edward.scissorhands@example.com",
        "interests": ["Art", "Music", "Technology"],
        "community_ids": [1, 3, 2],
    },
    {
        "id": 9,
        "username": "fiona_shrek",
        "email": "fiona.shrek@example.com",
        "interests": ["Cooking", "Gardening", "Literature"],
        "community_ids": [5, 8],
    },
    {
        "id": 10,
        "username": "george_clooney",
        "email": "george.clooney@example.com",
        "interests": ["Cinema", "Photography", "Travel"],
        "community_ids": [3, 7],
    },
    {
        "id": 11,
        "username": "hannah_montana",
        "email": "hannah.montana@example.com",
        "interests": ["Music", "Dance", "Fitness"],
        "community_ids": [1, 4],
    },
    {
        "id": 12,
        "username": "ian_fleming",
        "email": "ian.fleming@example.com",
        "interests": ["Literature", "Travel", "Technology"],
        "community_ids": [3, 2],
    },
    {
        "id": 13,
        "username": "julia_roberts",
        "email": "julia.roberts@example.com",
        "interests": ["Cinema", "Art", "Health"],
        "community_ids": [3, 1],
    },
    {
        "id": 14,
        "username": "kevin_bacon",
        "email": "kevin.bacon@example.com",
        "interests": ["Music", "Sports", "Technology"],
        "community_ids": [1, 2, 7],
    },
    {
        "id": 15,
        "username": "linda_carol",
        "email": "linda.carol@example.com",
        "interests": ["Cooking", "Art", "Photography"],
        "community_ids": [5, 3],
    },
    {
        "id": 16,
        "username": "michael_scott",
        "email": "michael.scott@example.com",
        "interests": ["Comedy", "Writing", "Sports"],
        "community_ids": [9, 7],
    },
    {
        "id": 17,
        "username": "nina_dobrev",
        "email": "nina.dobrev@example.com",
        "interests": ["Dance", "Health", "Travel"],
        "community_ids": [4, 5],
    },
    {
        "id": 18,
        "username": "oliver_twist",
        "email": "oliver.twist@example.com",
        "interests": ["Literature", "Cooking", "Music"],
        "community_ids": [3, 5],
    },
    {
        "id": 19,
        "username": "paula_abdul",
        "email": "paula.abdul@example.com",
        "interests": ["Dance", "Fitness", "Music"],
        "community_ids": [4, 1],
    },
    {
        "id": 20,
        "username": "quincy_jones",
        "email": "quincy.jones@example.com",
        "interests": ["Music", "Technology", "Cinema"],
        "community_ids": [1, 2, 3],
    },
    {
        "id": 21,
        "username": "rachel_green",
        "email": "rachel.green@example.com",
        "interests": ["Fashion", "Photography", "Art"],
        "community_ids": [3, 8],
    },
    {
        "id": 22,
        "username": "steve_jobs",
        "email": "steve.jobs@example.com",
        "interests": ["Technology", "Innovation", "Design"],
        "community_ids": [2, 10],
    },
    {
        "id": 23,
        "username": "tina_fey",
        "email": "tina.fey@example.com",
        "interests": ["Comedy", "Writing", "Cinema"],
        "community_ids": [9, 3],
    },
    {
        "id": 24,
        "username": "ursula_le_guin",
        "email": "ursula.leguin@example.com",
        "interests": ["Literature", "Art", "Photography"],
        "community_ids": [3, 8],
    },
    {
        "id": 25,
        "username": "victor_frankenstein",
        "email": "victor.frankenstein@example.com",
        "interests": ["Science", "Technology", "Literature"],
        "community_ids": [2, 3],
    },
    {
        "id": 26,
        "username": "wendy_darling",
        "email": "wendy.darling@example.com",
        "interests": ["Travel", "Literature", "Art"],
        "community_ids": [3, 4],
    },
    {
        "id": 27,
        "username": "xander_harris",
        "email": "xander.harris@example.com",
        "interests": ["Gaming", "Technology", "Health"],
        "community_ids": [2, 11],
    },
    {
        "id": 28,
        "username": "yvonne_starr",
        "email": "yvonne.starr@example.com",
        "interests": ["Music", "Fashion", "Photography"],
        "community_ids": [1, 8],
    },
    {
        "id": 29,
        "username": "zachary_levi",
        "email": "zachary.levi@example.com",
        "interests": ["Acting", "Dance", "Cinema"],
        "community_ids": [9, 3],
    },
    {
        "id": 30,
        "username": "amber_heard",
        "email": "amber.heard@example.com",
        "interests": ["Acting", "Art", "Travel"],
        "community_ids": [3, 4],
    },
    {
        "id": 31,
        "username": "bruce_wayne",
        "email": "bruce.wayne@example.com",
        "interests": ["Business", "Technology", "Fitness"],
        "community_ids": [2, 5],
    },
    {
        "id": 32,
        "username": "catherine_zeta",
        "email": "catherine.zeta@example.com",
        "interests": ["Acting", "Dance", "Health"],
        "community_ids": [9, 4],
    },
    {
        "id": 33,
        "username": "daniel_radcliffe",
        "email": "daniel.radcliffe@example.com",
        "interests": ["Acting", "Literature", "Travel"],
        "community_ids": [3, 4],
    },
]

COMMUNITIES = [
    {
        "id": 1,
        "name": "Music Lovers",
        "description": "A community for people who love all genres of music.",
        "interests": ["Music", "Concerts", "Live Performances"],
    },
    {
        "id": 2,
        "name": "Tech Enthusiasts",
        "description": "Discuss the latest in technology and innovation.",
        "interests": ["Technology", "Coding", "Gadgets"],
    },
    {
        "id": 3,
        "name": "Art & Photography",
        "description": "Share and appreciate art and photography.",
        "interests": ["Art", "Photography", "Creative Writing"],
    },
    # Additional 30 Communities
    {
        "id": 4,
        "name": "Health and Wellness",
        "description": "A community focused on healthy living and wellness.",
        "interests": ["Health", "Fitness", "Nutrition"],
    },
    {
        "id": 5,
        "name": "Culinary Arts",
        "description": "Explore the world of cooking and gastronomy.",
        "interests": ["Cooking", "Baking", "Food Photography"],
    },
    {
        "id": 6,
        "name": "DIY Crafts",
        "description": "For those who love to create and build things themselves.",
        "interests": ["DIY", "Crafting", "Home Improvement"],
    },
    {
        "id": 7,
        "name": "Sports Fans",
        "description": "Discuss your favorite sports and teams.",
        "interests": ["Sports", "Fitness", "Outdoor Activities"],
    },
    {
        "id": 8,
        "name": "Creative Writers",
        "description": "A place for writers to share and critique their work.",
        "interests": ["Writing", "Literature", "Storytelling"],
    },
    {
        "id": 9,
        "name": "Comedy Club",
        "description": "Share jokes, funny stories, and enjoy a good laugh.",
        "interests": ["Comedy", "Humor", "Stand-up"],
    },
    {
        "id": 10,
        "name": "Innovators Hub",
        "description": "Collaborate on innovative projects and ideas.",
        "interests": ["Innovation", "Entrepreneurship", "Technology"],
    },
    {
        "id": 11,
        "name": "Gaming Zone",
        "description": "Discuss the latest games and gaming strategies.",
        "interests": ["Gaming", "Esports", "Game Development"],
    },
    {
        "id": 12,
        "name": "Book Club",
        "description": "Read and discuss books across various genres.",
        "interests": ["Reading", "Literature", "Discussion"],
    },
    {
        "id": 13,
        "name": "Travel Enthusiasts",
        "description": "Share travel experiences and tips.",
        "interests": ["Travel", "Adventure", "Culture"],
    },
    {
        "id": 14,
        "name": "Photography Masters",
        "description": "Enhance your photography skills and share your work.",
        "interests": ["Photography", "Editing", "Creative Arts"],
    },
    {
        "id": 15,
        "name": "Fitness Freaks",
        "description": "Stay motivated and share fitness routines.",
        "interests": ["Fitness", "Workout", "Health"],
    },
    {
        "id": 16,
        "name": "Tech Innovators",
        "description": "Explore cutting-edge technology and innovations.",
        "interests": ["Technology", "Innovation", "Gadgets"],
    },
    {
        "id": 17,
        "name": "Music Producers",
        "description": "Collaborate and discuss music production techniques.",
        "interests": ["Music Production", "Sound Engineering", "Beats"],
    },
    {
        "id": 18,
        "name": "Nature Lovers",
        "description": "Appreciate and protect the beauty of nature.",
        "interests": ["Nature", "Hiking", "Environmentalism"],
    },
    {
        "id": 19,
        "name": "Entrepreneurs Network",
        "description": "Connect with like-minded entrepreneurs.",
        "interests": ["Entrepreneurship", "Business", "Startups"],
    },
    {
        "id": 20,
        "name": "Language Learners",
        "description": "Learn and practice new languages together.",
        "interests": ["Languages", "Education", "Cultural Exchange"],
    },
    {
        "id": 21,
        "name": "Mindfulness & Meditation",
        "description": "Practice mindfulness and meditation techniques.",
        "interests": ["Meditation", "Mindfulness", "Mental Health"],
    },
    {
        "id": 22,
        "name": "Science Explorers",
        "description": "Dive into the wonders of science and discovery.",
        "interests": ["Science", "Research", "Astronomy"],
    },
    {
        "id": 23,
        "name": "Fashion Forward",
        "description": "Stay updated with the latest fashion trends.",
        "interests": ["Fashion", "Design", "Styling"],
    },
    {
        "id": 24,
        "name": "Film Buffs",
        "description": "Discuss and review the latest films.",
        "interests": ["Cinema", "Film Reviews", "Directing"],
    },
    {
        "id": 25,
        "name": "Coding Dojo",
        "description": "Improve your coding skills through practice and collaboration.",
        "interests": ["Coding", "Programming", "Software Development"],
    },
    {
        "id": 26,
        "name": "Pet Lovers",
        "description": "Share stories and tips about your furry friends.",
        "interests": ["Pets", "Animal Care", "Pet Training"],
    },
    {
        "id": 27,
        "name": "Astronomy Club",
        "description": "Explore the universe and celestial events.",
        "interests": ["Astronomy", "Space", "Stargazing"],
    },
    {
        "id": 28,
        "name": "Urban Explorers",
        "description": "Discover and document urban landscapes.",
        "interests": ["Urban Exploration", "Photography", "Architecture"],
    },
    {
        "id": 29,
        "name": "Sustainable Living",
        "description": "Promote and discuss sustainable lifestyle choices.",
        "interests": ["Sustainability", "Eco-friendly", "Green Living"],
    },
    {
        "id": 30,
        "name": "Creative Coding",
        "description": "Combine creativity with coding projects.",
        "interests": ["Creative Coding", "Artistic Programming", "Interactive Design"],
    },
    {
        "id": 31,
        "name": "Digital Nomads",
        "description": "Connect with fellow digital nomads around the world.",
        "interests": ["Remote Work", "Travel", "Lifestyle"],
    },
    {
        "id": 32,
        "name": "Book Writers",
        "description": "Collaborate and share insights on writing books.",
        "interests": ["Writing", "Publishing", "Storytelling"],
    },
    {
        "id": 33,
        "name": "Eco Warriors",
        "description": "Advocate for environmental protection and activism.",
        "interests": ["Environmentalism", "Activism", "Sustainability"],
    },
]
